In [4]:
from pycaret.classification import *

import cuml
cuml.common.logger.set_level(0)

import pandas as pd

# Load the dataset
data = pd.read_csv('train.csv')
new_data = pd.read_csv('test.csv')

# Initialize the setup
clf_setup = setup(data, target='labels', use_gpu = True, fold_shuffle=True)

In [8]:
# # Compare models
# best_models = compare_models()

# # Print the best models
# print(best_models)

In [3]:

# Create the KNN model
knn = create_model('knn')
tuned_knn = tune_model(knn, choose_better = True, n_iter=1500)
print(tuned_knn)
# KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='manhattan',
#                      metric_params=None, n_jobs=-1, n_neighbors=31, p=2,
#                      weights='distance')

Fitting 10 folds for each of 300 candidates, totalling 3000 fits
KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='manhattan',
                     metric_params=None, n_jobs=-1, n_neighbors=16, p=2,
                     weights='distance')

In [10]:
# Create the Random Forest model
nb = create_model('nb')
tuned_nb = tune_model(nb, choose_better = True, n_iter=1500, optimize="F1")
print(tuned_nb)
# GaussianNB(priors=None, var_smoothing=1)

Fitting 10 folds for each of 28 candidates, totalling 280 fits
GaussianNB(priors=None, var_smoothing=1)

In [1]:
# Create the Light XGBoost model
lightgbm = create_model('lightgbm')
tuned_lightgbm = tune_model(lightgbm, choose_better = True, n_iter=150, optimize="F1")
print(tuned_lightgbm)
# LGBMClassifier(bagging_fraction=0.8, bagging_freq=7, boosting_type='gbdt',
#                class_weight=None, colsample_bytree=1.0, feature_fraction=0.6,
#                importance_type='split', learning_rate=0.1, max_depth=-1,
#                min_child_samples=66, min_child_weight=0.001, min_split_gain=0.3,
#                n_estimators=290, n_jobs=-1, num_leaves=70, objective=None,
#                random_state=8623, reg_alpha=0.5, reg_lambda=0.01, silent='warn',
#                subsample=1.0, subsample_for_bin=200000, subsample_freq=0)

NameError: name 'create_model' is not defined

In [5]:
xgb = create_model('xgboost')
tuned_xgb = tune_model(xgb, choose_better = True, n_iter=150)
print(tuned_xgb)

Fitting 10 folds for each of 150 candidates, totalling 1500 fits
XGBClassifier(base_score=None, booster='gbtree', callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.7, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.1, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=7, max_leaves=None,
              min_child_weight=4, missing=nan, monotone_constraints=None,
              n_estimators=270, n_jobs=-1, num_parallel_tree=None,
              objective='binary:logistic', predictor=None, ...)

In [ ]:
# Create the voting classifier
# voting_classifier = blend_models(estimator_list=[tuned_knn, tuned_nb, tuned_lightgbm])

In [6]:
print(tuned_xgb)

XGBClassifier(base_score=None, booster='gbtree', callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.7, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.1, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=7, max_leaves=None,
              min_child_weight=4, missing=nan, monotone_constraints=None,
              n_estimators=270, n_jobs=-1, num_parallel_tree=None,
              objective='binary:logistic', predictor=None, ...)

In [ ]:
# Make predictions on new data
# predictions = predict_model(tuned_knn, data=new_data)
# predict_df = predictions[['id', 'prediction_label']]
# predict_df.to_csv(r'submission_knn.csv',index=False)